name: Deploy Frontend
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - run: docker build -t serge1989/react-test -f Dockerfile.dev .
            - run: docker run -e CI=true serge1989/react-test npm test

            - name: Generate deployment package
              run: zip -r deploy.zip . -x '*.git*'

              #- name: Deploy to EB
              #uses: username/beanstalk-deploy@v18
              #with:
              #    aws_access_key: ${{ }}
              #    aws_secret_key: ${{ }}
              #    appliaction_name: docker-gh
              #    environment_name: Dockergh-env
              #    existing_bucket_name: elasticbeanstalk-us-east-1-9222
              #    region: us-east-1
              #    version_label: ${{ github.sha }}
              #    deployment_package: deploy.zip
